"""
mypipeline
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from airflow.models import Variable
from astro import sql as aql
import pandas as pd
import pendulum

from airflow.models import Variable
import requests

@aql.dataframe(task_id="fetch_activity")
def fetch_activity_func():
    r = requests.get(Variable.get('API'))
    return r.json()

@aql.dataframe(task_id="print_activity")
def print_activity_func(fetch_activity: pd.DataFrame):
    print('fetch_activity')

@dag(
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2023-07-04", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
)
def mypipeline():
    fetch_activity = fetch_activity_func()

    print_activity = print_activity_func(
        fetch_activity,
    )

dag_obj = mypipeline()
